title = "North Carolina Infectious Diseases Society"
baseURL = "https://www.ncidsociety.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/favicon.ico"
  site_logo = "images/android-chrome-192x192.png"
  description = "Infectious Diseases in North Carolina"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  mainSections = [] # This tells Ananke which sections to show in nav automatically

[[params.ananke_socials]]
name = "github"
url = "https://github.com/wf-id/ncidsociety"
label = "ncidsociety github"


[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "bylaws"
    url = "/bylaws/"
    weight = 20
  [[menu.main]]
    name = "leadership"
    url = "/leadership/"
    weight = 30
  [[menu.main]]
    name = "membership"
    url = "/membership/"
    weight = 40
  [[menu.main]]
    name = "resources"
    url = "/resources/"
    weight = 50
  [[menu.main]]
    name = "sponsors"
    url = "/sponsors/"
    weight = 60
  [[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 70
  [[menu.main]]
    name = "members"
    url = "/members/"
    weight = 100
  


[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true